name: test
on: [push]
jobs:     
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        if: matrix.dv == 'a'
      - run: cat 2.txt
        if: cancelled()
  test:
    needs: [build]
    runs-on: windows-latest
    steps:
     - run: echo test
   
  test2:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo test2
