name: test
on:
  check_suite:
    types: [completed, rerequested]
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: cat 2.txt
