name: test
on: [push]
jobs:     
  build:
    strategy:
      matrix:
        dv: [a, b]
        cv: [c, d]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        if: matrix.dv == 'a'
      - run: cat 2.txt
        if: cancelled()
