name: test
on: [push]
jobs:     
  build:
    strategy:
      matrix:
        os: ${{ env.dv }}
    env:
      dv: '[windows-latest,ubuntu-latest]'
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - run: cat 2.txt
