name: test
on:
  pull_request:
    branches: 
      - master
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: cat 2.txt
